# yaml-language-server: $schema=https://github.com/senz/cheatsheet-generator/raw/master/build-schema.json
---
include:
  - config: config.example.yml
    config-name: Example config
    artifact-name: example-cheatsheet

  - config: cat.config.yml
    config-name: Categories Config
    artifact-name: Cat-Config 
