name: Test config build

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: read-all
jobs:
  build:
    uses: ./.github/workflows/build-user-config.yml
    with:
      build_matrix_path: .github/test-data/build.yaml
      config_path: .github/test-data/config
      archive_name: example-cheatsheet
